services:
  app:
    build:
      context: ./deploy/docker
      dockerfile: Dockerfile
    container_name: academic-test
    ports:
      - "8080:80"
    volumes:
      - ${HOST_BASE_PATH}:/base
      - ./deploy/docker/entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped